### ISSUE TITLE
Disable Stage Transitions in Naruto Shippuuden: Gekitou Ninja Taisen! EX 2

### ISSUE THREAD

**Issue by GunBlazer** [NicholasMoser/Naruto-GNT-Modding#11]
Unlike its predecessor, _Naruto Shippuuden: Gekitou Ninja Taisen! EX 2_ includes the ability to disable stage elements such as Obstacles and Hazards. However, the game still forces Stage Transitions to be enabled and no way to select the alternate Stage variants on their own.

**Comment by NicholasMoser** [comment]
Can you try this?

`040c7d64 4e800020`

**Comment by GunBlazer** [comment]
Seems to work with no repercussions. Closing the issue.

**Comment by NicholasMoser** [comment]
Added with https://github.com/NicholasMoser/Naruto-GNT-Modding/commit/fcb6ab8b5fa522539336876a4fbcaa8f18fcb207
