### ISSUE TITLE
Code Requests GNT4

### ISSUE THREAD

**Issue by TheCape77** [NicholasMoser/Naruto-GNT-Modding#2]
1. Select same character in 3MC
2. Have the game load and select up to 6 costumes
3. Able to replace Karasu and Akamaru on the character select screen with other characters without affecting Kiba and Kankuro
4. Ability to load and select different SEQ files
5. Ability to change or map controls. Alternately make Z do A+B

**Comment by NicholasMoser** [comment]
I have created issues in GNTool for each of these for better issue tracking:
[Select same character in 3MC](https://github.com/NicholasMoser/GNTool/issues/21)
[Have the game load and select up to 6 costumes](https://github.com/NicholasMoser/GNTool/issues/22)
[Able to replace Karasu and Akamaru on the character select screen with other characters without affecting Kiba and Kankuro](https://github.com/NicholasMoser/GNTool/issues/23)

I've removed "Ability to change or map controls. Alternately make Z do A+B" for now, as discussing with you it seems to not be necessary.
