### ISSUE TITLE
Analyze GNT4 savefile structure

### ISSUE THREAD

**Issue by GunBlazer** [NicholasMoser/Naruto-GNT-Modding#3]
And discern how to make a modded version's save completely distinct from a vanilla one.

**Comment by NicholasMoser** [comment]
I haven't figured out the savefile structure yet, but I do have something relating to this worth sharing.

The functions in the game that check whether or not something is unlocked have been [found and decompiled](https://github.com/doldecomp/gnt4/blob/master/src/unlock.c). I've also added functionality to [GNTool 3.5](https://github.com/NicholasMoser/GNTool/releases/tag/3.5) that makes these functions always return true. Therefore using GNTool 3.5 you can make the game believe that everything is unlocked, even if the save data does not indicate so.

**Comment by NicholasMoser** [comment]
I'm going to close this issue now. You can have a separate save by having a separate game ID which SCON4 has done.

The important parts of the save data structure have now also been solved, and there are codes to unlock everything in it. See:

- https://github.com/NicholasMoser/Naruto-GNT-Modding/blob/master/gnt4/docs/guides/gecko_codes.md#unlock-everything-nick
- https://github.com/NicholasMoser/Naruto-GNT-Modding/blob/master/gnt4/docs/guides/gecko_codes.md#unlock-everything-nick-1
