### ISSUE TITLE
GNT Special address and function

### ISSUE THREAD

**Issue by Gtrrevolution** [NicholasMoser/Naruto-GNT-Modding#35]
Hi,
I'm trying to use the code on my dolphin emulator however, I don't understand how I can apply the character state flags code to the game. I'm looking to remove the x hit animation to the character. Please help.

**Comment by NicholasMoser** [comment]
> I don't understand how I can apply the character state flags code to the game

Which code? This one? https://github.com/NicholasMoser/Naruto-GNT-Modding/blob/main/gntsp/docs/guides/gecko_codes.md#no-invincibility-on-backstepssidesteps-nick

If you google "How to add a Gecko code to dolphin" there are pretty good guides on how to. But put simply you right click on the game icon in Dolphin and select properties. Go to the Gecko Codes tab and hit Add New Code. Put the code in the Code text box and put whatever you want in the rest of the boxes (I recommend giving it a name you'll remember).

> I'm looking to remove the x hit animation to the character.

That's a bit more complicated. What exactly are you trying to do?
