### ISSUE TITLE
Rev 1 code requests

### ISSUE THREAD

**Issue by mitchellhumphrey** [NicholasMoser/Naruto-GNT-Modding#6]
Posting so remembered

Requesting a code for Rev1 for disabling obstacles, and one for disabling stage transitions.

**Comment by NicholasMoser** [comment]
So I think I can disable stage transitions, but it will likely be a lot of work to disable obstacles. The logic for enable and disable obstacles is inside of the stage SEQ file, e.g. `DATA\files\stg\004\0000.seq`

If I could get Rev3 stages working in Rev1 it would be easy to disable obstacles. I tried just copying the entire stage FPK file from Rev3 to Rev1, but didn't have much luck:

![image](https://user-images.githubusercontent.com/4983605/148881367-5a432f47-af23-444c-b6ea-dcc76575c484.png)

**Comment by NicholasMoser** [comment]
Pretty sure I got both working:

```
Disable Stage Transition
040b9f8c 4e800020

Disable Stage Obstacles
040aff3c 38000001
040aff40 901f02ac
C20358A0 00000009
80630000 2C0304A2
41820034 2C0304A3
4182002C 2C0304A4
41820024 2C0304A5
4182001C 2C030480
41820014 2C030481
4182000C 2C030472
40820008 3860FFFF
60000000 00000000
```

Codes have been added here: https://github.com/NicholasMoser/Naruto-GNT-Modding/blob/master/rev1/docs/guides/gecko_codes.md
